

---
output:
  html_document: default
  pdf_document:
    fig_caption: yes
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.width=5, fig.height=5,fig.align = "center",cache=TRUE)
```


```{r, echo=FALSE, include=FALSE, warning=FALSE, message=FALSE}
##libraries, globals

library(ggplot2)
library(reshape)
library(grid)
library(dplyr)
library(gridExtra)
library(lme4)

paper_theme <- theme(
  panel.grid.major = element_blank(), 
  panel.grid.minor = element_blank(), 
  panel.background = element_blank(),
  axis.title.x = element_text(size=18),
  axis.text.x=element_text(colour="black", 
                           size = 14), 
  axis.title.y = element_text(size = 18, vjust = 1),
  axis.text.y  = element_text(size = 14),
  axis.line.x = element_line(colour = "black"), 
  axis.line.y = element_line(colour = "black"),
  legend.text=element_text(size=16),
  strip.text=element_blank(),
          strip.background = element_blank())

paper_theme_2 <- theme_light() + theme(axis.title.x = element_text(size=18),
  axis.text.x=element_text(colour="black", 
                           size = 14), 
  axis.title.y = element_text(size = 18, vjust = 1),
  axis.text.y  = element_text(size = 14))

paper_theme_3 <- theme( axis.title.x = element_text(size=18),
  axis.text.x=element_text(colour="black", 
                           size = 14), 
  axis.title.y = element_text(size = 18, vjust = 1),
  axis.text.y  = element_text(size = 14),
  strip.text=element_text(size=16),
  axis.line.x = element_line(colour = "black"), 
  axis.line.y = element_line(colour = "black"),
  legend.title=element_text(size=18),
  legend.text=element_text(size=16))  


binomial_smooth <- function(...) {
  geom_smooth(method = "glm", method.args = list(family = "binomial"), ...)
}
```

```{r, include=FALSE, echo=FALSE, warning=FALSE,message=FALSE}

data.estimation.resp.loc <- read.csv("data/estimation_dot_gaze.csv", sep="\t")
data.estimation.tracker <- read.csv("data/estimation_tracker_data.csv", sep="\t")
data.estimation.tracker$trial_id <- data.estimation.tracker$trial_id - 1
data.estimation.resp.loc$trial_id <- data.estimation.resp.loc$trial_id - 1


data.estimation.resp.loc <- data.estimation.resp.loc %>%
                filter(belowX >= 0)

trials <- (unique(data.estimation.resp.loc$trial_id))

data.estimation.tracker <- data.estimation.tracker %>%
                group_by(trial_id) %>%
                filter(trial_id %in% trials)


data.estimation.resp.loc$id <- seq.int(1, nrow(data.estimation.resp.loc))


data.estimation.resp <- data.estimation.resp.loc %>%
            group_by(Trial, Time, pid) %>%
            top_n(n=1, wt=id) %>%
            group_by(Dots_Counted, Dots_Shown, pid) %>%
            mutate(err=Dots_Counted - Dots_Shown) %>%
            mutate(abs_err = abs(err)) %>%
            mutate(over = 1*(Dots_Counted > Dots_Shown)) %>%
            mutate(under = 1*(Dots_Shown > Dots_Counted)) %>%
            mutate(corr= 1*(Dots_Counted == Dots_Shown)) %>%
            filter(Dots_Counted < 201)


data.estimation.tracker <- data.estimation.tracker %>%
                  filter(ValidityLeft == 0 & ValidityRight == 0) %>%

                mutate(av_x = (GazePointXLeft +GazePointXRight)/2) %>%
                mutate(av_y = (GazePointYLeft +GazePointYRight)/2) %>%
                group_by(trial_id) %>%
                mutate(Time = round(max(TimeStamp)/100)/10)

data.estimation.tracker$id <- seq.int(1,nrow(data.estimation.tracker))

data.estimation.resp.old <- cbind(data.estimation.resp)
data.estimation.resp.loc$Time <- as.factor(round(data.estimation.resp.loc$Time,2))

```

```{r, include=FALSE}


data.discrimination.resp.loc <- read.csv("data/discrimination_dot_gaze.csv", sep="\t")
data.discrimination.tracker <- read.csv("data/discrimination_tracker_data.csv", sep="\t")
data.discrimination.tracker$trial_id <- floor((data.discrimination.tracker$trial_id - 1)/2)
data.discrimination.resp.loc$trial_id <- data.discrimination.resp.loc$trial_id - 1

length(unique(data.discrimination.tracker$trial_id))

data.discrimination.resp.loc <- data.discrimination.resp.loc %>%
                filter(belowX >= 0)
trials <- (unique(data.discrimination.resp.loc$trial_id))
data.discrimination.tracker <- data.discrimination.tracker %>%
                group_by(trial_id) %>%
                filter(trial_id %in% trials)


data.discrimination.resp.loc$id <- seq.int(1, nrow(data.discrimination.resp.loc))
data.discrimination.resp.loc$Score <- as.numeric(data.discrimination.resp.loc$Score) - 1



data.discrimination.resp <- data.discrimination.resp.loc %>%
            group_by(Trial, Time1, Time2, pid) %>%
            mutate(cond=paste(round(Time1),round(Time2),sep="_")) %>%
            top_n(n=1, wt=id)  %>%
            group_by(Dots_Shown1, Dots_Shown2) %>%
            mutate(ratio = (Dots_Shown1 - Dots_Shown2)/(Dots_Shown1**2 + Dots_Shown2**2) ** 0.5)  

data.discrimination.resp$Dots_Counted <- data.discrimination.resp$Dots_Counted - 1
head(data.discrimination.resp)

data.discrimination.resp.vary <- subset(data.discrimination.resp, data.discrimination.resp$Time1 != data.discrimination.resp$Time2)


data.discrimination.tracker <- data.discrimination.tracker %>%
                  filter(ValidityLeft == 0 & ValidityRight == 0) %>%

                mutate(av_x = (GazePointXLeft +GazePointXRight)/2) %>%
                mutate(av_y = (GazePointYLeft +GazePointYRight)/2) %>%
                group_by(trial_id) %>%
                mutate(Time = round(max(TimeStamp)/100)/10)

data.discrimination.tracker$id <- seq.int(1,nrow(data.discrimination.tracker))

data.discrimination.resp.old <- cbind(data.discrimination.resp)
```



```{r}

data.discrimination.resp <- cbind(data.discrimination.resp.old)
data.estimation.resp <- cbind(data.estimation.resp.old)

#data.discrimination.resp$Time <- as.factor(round(data.discrimination.resp$Time1,2))
data.discrimination.resp$Score <- as.numeric(as.character(data.discrimination.resp$Score))

data.estimation.resp$Time <- as.factor(round(data.estimation.resp$Time,2))

data.discrimination.resp$cond <- plyr::mapvalues(data.discrimination.resp$cond, from = c("0_0", "0_1", "1_0", "1_1"), to = c("Short_Short", "Short_Long", "Long_Short", "Long_Long"))



data.estimation.resp.avs <- data.estimation.resp.loc %>%
                   group_by(Trial_End) %>%
                  filter(Trial_End >= 1523639984) %>%
                  filter(gazeDist > 0 & Dots_Shown < 150 & Dots_Shown >= 10) %>%
                  mutate(err=Dots_Counted - Dots_Shown) %>%
                  mutate(abs_err = abs(err)) %>%
                  mutate(within_x = 1/(1 + exp(-0.1*belowX))) %>%
                  group_by(trial_id) %>% 
                  mutate(belowX = mean(belowX)) %>%
                  mutate(within_x = mean(within_x)) %>%
                  mutate(within_x_tot = sum(within_x)) %>%
                  mutate(mean_dist=sum(gazeDist)/Dots_Shown) %>%
                  mutate(mean_abs_err = mean(abs_err)) %>%
                  mutate(pct_err=err/Dots_Shown) %>%
                  mutate(abs_pct_err=abs_err/Dots_Shown) %>%
                  top_n(n=1, wt=id) %>% 
                  filter(abs_pct_err < 1.0) %>%
                  filter(within_x > 0) 

data.estimation.resp.avs$seen_shown_diff <- data.estimation.resp.avs$within_x_tot - data.estimation.resp.avs$Dots_Shown
data.estimation.resp.avs$abs_seen_shown_diff <- abs(data.estimation.resp.avs$seen_shown_diff)
data.estimation.resp.avs$seen_shown_rat <- (data.estimation.resp.avs$within_x_tot)/data.estimation.resp.avs$Dots_Shown
data.estimation.resp.avs$abs_seen_shown_rat <- abs(data.estimation.resp.avs$seen_shown_rat)

 


data.discrimination.resp.avs <- data.discrimination.resp.loc %>%
                  group_by(Trial_End) %>%
                  filter(Trial_End >= 1523639984) %>%
                  filter(gazeDist > 0) %>%
                  group_by(trial_id, which_array) %>%
                  mutate(arr1 = (which_array==1)*1) %>%
                  mutate(arr2 = (which_array==2)*1) %>%
                  mutate(belowX1 = mean(belowX) * arr1) %>%
                  mutate(belowX2 = mean(belowX) * arr2)%>%
                  mutate(within_x1 =  sum(arr1/(1 + exp(-0.1*belowX)))) %>%
                  mutate(within_x2 =  sum(arr2/(1 + exp(-0.1*belowX)))) %>%
                  top_n(n=1, wt=id)%>%
                  group_by(trial_id) %>%
                  mutate(belowX1 = max(belowX1)) %>%
                  mutate(belowX2 = max(belowX2)) %>%
                  mutate(within_x1 = max(within_x1)) %>%
                  mutate(within_x2=max(within_x2)) %>%
                  top_n(n=1, wt=id) %>%
                  mutate(cond=paste(round(Time1),round(Time2),sep="_")) %>%
                  mutate(within_x_diff = (within_x1 - within_x2)) %>%
                  mutate(within_x_log_diff = (log(within_x1) - log(within_x2)))  %>%
                  mutate(abs_within_x_log_diff = abs(within_x_log_diff))  %>%
      
                  mutate(Dots_Counted = Dots_Counted - 1) %>%
                  mutate(Dots_Ratio = (Dots_Shown1 - Dots_Shown2)/(Dots_Shown1**2 + Dots_Shown2**2)**0.5) %>%
                  mutate(Abs_Dots_Ratio = abs(Dots_Ratio))
  

```


```{r, fig.width=7.5, fig.height=5}
 ggplot(data.estimation.resp.avs, aes(x=abs_seen_shown_diff, y=abs_pct_err)) +
        geom_point(aes(color=factor(Time)), alpha=0.35, size=2.) +
        stat_smooth(method="loess", se=FALSE, span=1, size=1.5) +
        xlab("Abs(Seen - Shown)") +
        ylab("Absolute error") +
           scale_color_discrete(name="Time") +
        theme_light() +    paper_theme_3 + facet_wrap(~Subject, scales="free_y")

 ggplot(data.estimation.resp.avs, aes(x=within_x, y=abs_pct_err)) +
        #geom_point(aes(color=factor(Time)), alpha=0.35, size=2.) +
        stat_summary_bin(fun.data="mean_cl_boot", bins=11) +
        stat_smooth(method="loess", se=TRUE, span=2, size=1.5) +
        xlab("Seen - Shown") +
        ylab("Error") +
           scale_color_discrete(name="Time") + scale_x_continuous(limits=range(data.estimation.resp.avs$within_x)) +
        theme_light() +    paper_theme_3 #+ facet_wrap(~Subject, scales="free_y")

```


