

---
output:
  html_document: default
  pdf_document:
    fig_caption: yes
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.width=5, fig.height=5,fig.align = "center",cache=TRUE)
```



```{r, echo=FALSE, include=FALSE, warning=FALSE, message=FALSE}
##libraries, globals
#library(plyr)
library(ggplot2)
library(reshape)
library(grid)
library(dplyr)
library(gridExtra)
library(lme4)

paper_theme <- theme(
  panel.grid.major = element_blank(), 
  panel.grid.minor = element_blank(), 
  panel.background = element_blank(),
  axis.title.x = element_text(size=18),
  axis.text.x=element_text(colour="black", 
                           size = 12), 
  axis.title.y = element_text(size = 18, vjust = 1),
  axis.text.y  = element_text(size = 12),
  axis.line.x = element_line(colour = "black"), 
  axis.line.y = element_line(colour = "black"),
  legend.text=element_text(size=16),
  strip.text=element_blank(),
          strip.background = element_blank())

paper_theme_2 <- theme_light() + theme(axis.title.x = element_text(size=18),
  axis.text.x=element_text(colour="black", 
                           size = 14), 
  axis.title.y = element_text(size = 18, vjust = 1),
  axis.text.y  = element_text(size = 14))

paper_theme_3 <- theme(
  axis.text.x=element_text(colour="black", 
                           size = 16), 
  axis.text.y  = element_text(size = 16, color="black"),

  axis.title.x = element_text(size = 20, color="black", face="plain"),
  axis.title.y = element_text(size = 20, color="black", face="plain"),
  strip.text=element_text(size=16),
  axis.line.x = element_line(colour = "black"), 
  axis.line.y = element_line(colour = "black"),
  legend.title=element_text(size=18),
  legend.text=element_text(size=14))  
binomial_smooth <- function(...) {
  geom_smooth(method = "glm", method.args = list(family = "binomial"), ...)
}

probit_smooth <- function(...) {
  geom_smooth(method = "glm", method.args = list(family = binomial(link="probit")), ...)
}
```

```{r, include=FALSE}

data.resp.loc <- read.csv("data/discrimination_dot_gaze.csv", sep="\t")
data.tracker <- read.csv("data/discrimination_tracker_data.csv", sep="\t")
data.tracker$trial_id <- floor((data.tracker$trial_id - 1)/2)
data.resp.loc$trial_id <- data.resp.loc$trial_id - 1

length(unique(data.tracker$trial_id))

data.resp.loc <- data.resp.loc %>%
                filter(belowX >= 0)
trials <- (unique(data.resp.loc$trial_id))
data.tracker <- data.tracker %>%
                group_by(trial_id) %>%
                filter(trial_id %in% trials)


data.resp.loc$id <- seq.int(1, nrow(data.resp.loc))
data.resp.loc$Score <- as.numeric(data.resp.loc$Score) - 1



data.resp <- data.resp.loc %>%
            group_by(Trial, Time1, Time2, pid) %>%
            mutate(cond=paste(round(Time1),round(Time2),sep="_")) %>%
            top_n(n=1, wt=id)  %>%
            group_by(Dots_Shown1, Dots_Shown2) %>%
            mutate(ratio = (Dots_Shown1 - Dots_Shown2)/(Dots_Shown1**2 + Dots_Shown2**2) ** 0.5)  %>%
            mutate(ratio = (Dots_Shown1/Dots_Shown2))  %>%
            #mutate(ratio = (Dots_Shown1/(Dots_Shown1+Dots_Shown2)))  %>%

            mutate(ratio_2 = min(Dots_Shown1, Dots_Shown2)/max(Dots_Shown1, Dots_Shown2)) %>%
           # mutate(ratio_2 = max(Dots_Shown1, Dots_Shown2)/min(Dots_Shown1, Dots_Shown2)) %>%

            mutate(time_num1=as.numeric(as.character(Time1))) %>%
            mutate(time_num2=as.numeric(as.character(Time2))) 
data.resp$Dots_Counted <- data.resp$Dots_Counted - 1
head(data.resp)

data.resp.vary <- subset(data.resp, data.resp$Time1 != data.resp$Time2)


data.tracker <- data.tracker %>%
                  filter(ValidityLeft == 0 & ValidityRight == 0) %>%

                mutate(av_x = (GazePointXLeft +GazePointXRight)/2) %>%
                mutate(av_y = (GazePointYLeft +GazePointYRight)/2) %>%
                group_by(trial_id) %>%
                mutate(Time = round(max(TimeStamp)/100)/10)

data.tracker$id <- seq.int(1,nrow(data.tracker))

data.resp.cop <- cbind(data.resp)

f_get_weber <- function(whenst) {
  whomst <- whomst[1]
  df <- subset(data.resp.cop, as.numeric(as.character(data.resp.cop$pid)) == as.numeric(as.character(whenst)))
  reg <- glm(data=df, Score ~ ratio_2, family=binomial(link="probit"))
  return(1/(coef(reg)["Dots_Ratio"]))
}
data.resp$Score <- as.numeric(as.character(data.resp$Score)) - 1


data.resp.old <- cbind(data.resp)
```






```{r, echo=FALSE}
data.resp <- cbind(data.resp.old)

data.resp$cond <- plyr::mapvalues(data.resp$cond, from = c("0_0", "0_1", "1_0", "1_1"), to = c("Short_Short", "Short_Long", "Long_Short", "Long_Long"))
data.resp$cond2 <- plyr::mapvalues(data.resp$cond, from = c("Short_Short", "Short_Long", "Long_Short", "Long_Long"), to = c(0, 0, 1,1))
data.resp$cond2 <- as.numeric(as.character(data.resp$cond2))

data.resp <- data.resp %>%
            mutate(ss=(cond=="Short_Short")*1) %>%
            mutate(sl=(cond=="Short_Long")*1) %>%
            mutate(ls=(cond=="Long_Short")*1) %>%
            mutate(ll=(cond=="Long_Long")*1) %>%
            group_by(ratio) %>%
            mutate(ratio_p = ratio) %>%
            group_by(cond) %>%
            arrange(ratio) %>%
           # rowwise() %>%
            mutate(mean_rat = cumsum(Dots_Counted)) %>%
            mutate(mean_rat =cumsum(Dots_Counted)) %>%
            mutate(mean_rat= cumsum(Dots_Counted)) %>%
            mutate(mean_rat =cumsum(Dots_Counted )) 



                    


ggplot(data=data.resp, aes(x=abs(ratio), y=Score)) +
          #stat_summary_bin(bins=10, fun.data="mean_cl_boot") +
        binomial_smooth() +
        paper_theme +
            xlab("")  + ylab("p(correct)")


ggplot(data=subset(data.resp, data.resp$Time1 == data.resp$Time2), 
        aes(x=ratio_2, y=Score, group=cond, color=cond)) +
          stat_summary_bin(bins=10, fun.data="mean_cl_boot") +
            binomial_smooth() +
            theme_light() + paper_theme_3 +
            xlab("")  + ylab("p(correct)")


#summary(glmer(data=data.resp.vary, Dots_Counted ~ ratio + cond + #(1|Subject), family=binomial(link="probit")))

#levels(factor(data.resp$cond))
#data.resp$cond <-factor(data.resp$cond, levels = levels(factor(data.resp$cond))[c(2,1,3)])

data.resp.novary <- subset(data.resp, data.resp$Time1 == data.resp$Time2)
data.resp.vary <- subset(data.resp, data.resp$Time1 != data.resp$Time2)


data.resp.binned.vary <- data.resp.vary %>%
              mutate(ratio3 = Dots_Shown1/Dots_Shown2) %>%
              mutate(rat_bins=round(ratio3, 1)) %>%
              group_by(rat_bins, Dots_Counted) %>%
              mutate(mean_rat=mean(cond2)) %>%
              top_n(n=1, wt=id)
               

r.1 <- glm(data=data.resp.novary, Dots_Counted ~ ratio * Time1,  family=binomial(link="probit"))
r.2 <- glm(data=data.resp.vary, Dots_Counted ~ ratio * Time1,  family=binomial(link="probit"))
#r.3 <- glm(data=data.resp, Dots_Counted ~ ratio * Time1 * Time2,  family=binomial(link="probit"))
r.3 <- glm(data=data.resp, Dots_Counted ~ ratio * Time1 * Time2,  family=binomial(link="probit"))

summary(r.1)

fit_resp <- predict(r.1, data=data.resp.novary, interval="prediction", type="response")
data.resp.novary$fitted <- fit_resp

ggplot(data=data.resp.novary, aes(x=ratio, y=fitted, color=cond)) +
            theme_light() + paper_theme_3 +
      geom_line(size=1.25, alpha=0.9)

fit_resp <- predict(r.2, data=data.resp.vary, interval="prediction", type="response")
data.resp.vary$fitted <- fit_resp

ggplot(data=data.resp.vary, aes(x=ratio, y=fitted, color=cond)) +
            theme_light() + paper_theme_3 +
      geom_line(size=1.25, alpha=0.9)

fit_resp <- predict(r.3, data=data.resp, interval="prediction", type="response")
data.resp$fitted <- fit_resp
data.resp <- data.resp %>%
             mutate(fitted_acc= (1-fitted) *  (Dots_Shown1 > Dots_Shown2) + (fitted) * (Dots_Shown2 > Dots_Shown1))

#ggplot(data=data.resp, aes(x=, y=fitted, color=cond)) +
       #     theme_light() + paper_theme_3 +
     # geom_line(size=1.25, alpha=0.9)

ggplot(data=data.resp, aes(x=ratio, y=fitted, group=cond, color=cond)) +
      geom_line(size=1.4) +
     # geom_point() +
    #  geom_vline(xintercept=0, color="white", size=5) +
       # stat_summary_bin(bins=7, fun.y="mean", geom="line")
            theme_light() + paper_theme_2 + theme(legend.title=element_blank()) + 
        xlab("Ratio") + ylab("Accuracy") 

ggplot(data=data.resp, aes(x=abs(ratio), y=fitted_acc, group=cond, color=cond)) +
     #geom_line(size=1.5) +
      # binomial_smooth(span=2) +
        #stat_summary_bin(binwidth=0.06, fun.y="mean", geom="line") +
        stat_summary_bin(binwidth=0.06, fun.data="mean_se", geom="errorbar") +

        #stat_summary(fun.y="mean", geom="line") +

            theme_light() + paper_theme_2 + xlab("Ratio") + ylab("Response") 
          #facet_wrap(~I(ratio>0), scales="free")


ggplot(data=data.resp, aes(x=ratio, y=Score, group=cond, color=cond)) +
     stat_summary_bin(bins=10, size=1.5) +
      # binomial_smooth(span=2) +
       # stat_summary_bin(bins=7, fun.y="mean", geom="line") +
            theme_light() + paper_theme_2 + xlab("Ratio") + ylab("Accuracy")

#ggplot(data=data.resp, 
        #aes(x=ratio_2, y=Score, group=cond, color=cond)) +
         # stat_summary_bin(bins=10, fun.data="mean_cl_boot") +
            #geom_smooth(se=FALSE, method="glm", method.args=list(family=binomial(link="probit")) )+
#
            #probit_smooth(se=FALSE) +
            #theme_light() + paper_theme_3 +
            #xlab("")  + ylab("p(correct)")


ggplot(data=data.resp, aes(x=cond, y= Score)) +
       stat_summary(fun.data="mean_se")



ggplot(data=data.resp, aes(x=ratio_2, y=Score)) +
        stat_summary_bin(fun.data="mean_cl_boot", bins=10) +
              theme_light() + paper_theme_3 +
             # probit_smooth(color="black", se=FALSE)+
             # probit_smooth(color="black", se=TRUE, alpha=0.3)+
              probit_smooth(se=FALSE)+
              probit_smooth(se=TRUE, alpha=0.3)+
              ylab("Accuracy") + 
              xlab("Absolute Ratio (Min/Max)") +
             ylim(0,1) 
        # +
           # scale_y_discrete(limits=c(0,1))

ggsave("figs/disc_score.pdf", width=5,height=5, dpi=400)
ggsave("figs/disc_score.png", width=5,height=5, dpi=400)

ggplot(data=data.resp, aes(x=Dots_Shown1/Dots_Shown2, y=1-Dots_Counted)) +
        stat_summary_bin(fun.data="mean_cl_boot", bins=11) +
              theme_light() + paper_theme_3 +   
               theme(legend.text=element_text(size=12), 
                     legend.position=c(0.85,0.8), legend.title=element_blank()) +
             # probit_smooth(color="black", se=FALSE)+
             # probit_smooth(color="black", se=TRUE, alpha=0.3)+
              probit_smooth(se=FALSE)+
              probit_smooth(se=TRUE, alpha=0.3)+
              scale_color_manual(values=c("blue", "red")) +
              ylab("p(choose 2)") + #xlab("Numerical Ratio") +
              xlab(expression(paste("Ratio ", (N[1] / N[2])))) +
             ylim(0,1)# +
            #facet_wrap(~I(Time1==Time2))

ggsave("figs/counted.pdf", width=5,height=5,dpi=400)


ggplot(data=data.resp, aes(x=Dots_Shown2/Dots_Shown1, y=Dots_Counted)) +
        stat_summary_bin(fun.data="mean_se", bins=11) +
              theme_light() + paper_theme_3 +   
               theme(legend.text=element_text(size=14), axis.text=element_text(size=16),axis.title=element_text(size=20),
                     legend.position=c(0.85,0.8), legend.title=element_blank()) +
             # probit_smooth(color="black", se=FALSE)+
             # probit_smooth(color="black", se=TRUE, alpha=0.3)+
              probit_smooth(se=FALSE)+
              probit_smooth(se=TRUE, alpha=0.3)+
              scale_color_manual(values=c("blue", "red")) +
              ylab("p(choose 2)") + #xlab("Numerical Ratio") +
              xlab(expression(paste("Numerical ratio  ", (N[2] / N[1])))) +
             ylim(0,1) + geom_hline(yintercept=0.5, linetype="dotted", size=1.5)
            #facet_wrap(~I(Time1==Time2))

ggsave("figs/counted.pdf", width=5,height=4.5,dpi=400)




ggplot(data=data.resp.vary, aes(x=Dots_Shown2/Dots_Shown1, y=Dots_Counted, color=cond)) +
  
        stat_summary_bin(fun.data="mean_se", bins=11, alpha=0.8, position=position_dodge(width=0.0)) +
       # stat_summary_bin(fun.y="mean", bins=9, geom="point") +
      #  geom_point(data=data.resp.binned.vary, aes(x=ratio3, y=0, color=mean_rat), size=5) +
      #  geom_point(data=data.resp.binned.vary, aes(x=ratio3, y=1, color=1-mean_rat),size=5) +

      # geom_jitter(width=0.01,height=0.01,alpha=0.9, size=1, shape=1) +
              theme_light() + paper_theme_3 +   
                 theme(legend.text=element_text(size=16), axis.text=element_text(size=16),axis.title=element_text(size=20),
                     legend.position=c(0.2,0.8), legend.title=element_blank()) +
              probit_smooth(aes(y=Dots_Counted), se=FALSE)+
              probit_smooth(aes(y=Dots_Counted),se=TRUE, alpha=0.3)+
              scale_color_manual(values=c("blue4", "green4")) +
              ylab("p(choose 2)") + #xlab("Numerical Ratio") +
              xlab(expression(paste("Numerical ratio ", (N[2] / N[1])))) +
            geom_hline(yintercept=0.5, size=1.5, linetype="dotted")
            # ylim(0,1) + 
           # xlim(0,1.55) +
           # coord_cartesian(xlim=c(0.63,1.61), ylim=c(0,1))
          #xlim(0.61,1.57)
            #facet_wrap(~I(Time1==Time2))

ggsave("figs/sl_ls.pdf", width=5, height=4.5,dpi=400)

ggplot(data=data.resp.novary, aes(x=Dots_Shown2/Dots_Shown1, y=Dots_Counted, color=cond)) +
  
        stat_summary_bin(fun.data="mean_se", bins=11, alpha=0.8, position=position_dodge(width=0.0)) +
       # stat_summary_bin(fun.y="mean", bins=9, geom="point") +
      #  geom_point(data=data.resp.binned.vary, aes(x=ratio3, y=0, color=mean_rat), size=5) +
      #  geom_point(data=data.resp.binned.vary, aes(x=ratio3, y=1, color=1-mean_rat),size=5) +

      # geom_jitter(width=0.01,height=0.01,alpha=0.9, size=1, shape=1) +
              theme_light() + paper_theme_3 +   
                 theme(legend.text=element_text(size=16), axis.text=element_text(size=16),axis.title=element_text(size=20),
                     legend.position=c(0.2,0.8), legend.title=element_blank()) +
              probit_smooth(aes(y=Dots_Counted), se=FALSE)+
              probit_smooth(aes(y=Dots_Counted),se=TRUE, alpha=0.3)+
              scale_color_manual(values=c("blue4", "green4")) +
              ylab("p(choose 2)") + #xlab("Numerical Ratio") +
              xlab(expression(paste("Numerical ratio ", (N[2] / N[1])))) +
              geom_hline(yintercept=0.5, size=1.5, linetype="dotted")

            # ylim(0,1) + 
           # xlim(0,1.55) +
           # coord_cartesian(xlim=c(0.63,1.61), ylim=c(0,1))
          #xlim(0.61,1.57)
            #facet_wrap(~I(Time1==Time2))

ggsave("figs/ss_ll.pdf", width=5, height=4.5,dpi=400)


ggplot(data=data.resp.novary, aes(x=ratio_2, y=Score)) +
        stat_summary_bin(fun.data="mean_se", bins=8) +
              theme_light() + paper_theme_3 +   
                 theme(legend.text=element_text(size=16), axis.text=element_text(size=16),axis.title=element_text(size=20),
                     legend.position=c(0.8,0.85), legend.title=element_blank()) +

              probit_smooth(se=FALSE)+
              probit_smooth(se=TRUE, alpha=0.3)+
              scale_color_manual(values=c("yellow3", "magenta4")) +

              ylab("Accuracy") + 
              xlab("Absolute Ratio (Min/Max)") +
            geom_hline(yintercept=0.5, linetype="dotted", size=1.5) +

             ylim(0,1) #+ coord_cartesian(xlim=c(0.6,1.0))
ggsave("figs/disc_score.pdf", width=5, height=4.5)


ggplot(data=data.resp.novary, aes(x=ratio_2, y=Score, group=cond, color=cond)) +
        stat_summary_bin(fun.data="mean_se", bins=8) +
              theme_light() + paper_theme_3 +   
                 theme(legend.text=element_text(size=16), axis.text=element_text(size=16),axis.title=element_text(size=20),
                     legend.position=c(0.8,0.85), legend.title=element_blank()) +

              probit_smooth(se=FALSE)+
              probit_smooth(se=TRUE, alpha=0.3, level=0.78)+
              scale_color_manual(values=c("yellow3", "magenta4")) +

              ylab("Accuracy") + 
              xlab("Absolute Ratio (Min/Max)") +
            geom_hline(yintercept=0.5, linetype="dotted", size=1.5) +
             ylim(0,1) #+ coord_cartesian(xlim=c(0.6,1.0))
        
ggsave("figs/ss_ll.pdf", width=5,height=4.5,dpi=400)
```


```{r, echo=FALSE, warning=FALSE, message=FALSE}


data.resp.avs <- data.resp.loc %>% 
                  filter(gazeDist > 0) %>%
                  group_by(trial_id, which_array) %>%
                  mutate(arr1 = (which_array==1)*1) %>%
                  mutate(arr2 = (which_array==2)*1) %>%
                  mutate(belowX1 = mean(belowX) * arr1) %>%
                  mutate(belowX2 = mean(belowX) * arr2)%>%
                  mutate(pathLength1 = mean(pathLength) * arr1) %>%
                  mutate(pathLength2 = mean(pathLength) * arr2)%>%
                  mutate(medFix1 = mean(medFix) * arr1) %>%
                  mutate(medFix2 = mean(medFix) * arr2) %>%
                  mutate(pctArea1 = mean(pctArea) * arr1) %>%
                  mutate(pctArea2 = mean(pctArea) * arr2) %>%
                  #mutate(within_x1 =  1/(1 + exp(-0.5 *belowX))) %>%
                  #mutate(within_x2 =   1/(1 + exp(-0.5 *belowX)))  %>%
  
                    mutate(within_x1 = 2/(1 + exp(-1 -0.25*belowX)) - 1) %>%
                      mutate(within_x2 = 2/(1 + exp(-1 -0.25*belowX)) - 1) %>%
                  # mutate(within_x1= arr1 * mean(pInGaze**0.2)) %>%
                  # mutate(within_x2= arr2 * mean(pInGaze**0.2)) %>%

                  mutate(within_x1 = arr1* sum(within_x1)) %>%
                  mutate(within_x2 = arr2*sum(within_x2)) %>%
                  top_n(n=1, wt=id)%>%
                  group_by(pid, Trial, Time1, Time2) %>%
                  mutate(pctArea1 = max(pctArea1)) %>%
                  mutate(pctArea2 = max(pctArea2)) %>%
                  mutate(belowX1 = max(belowX1)) %>%
                  mutate(belowX2 = max(belowX2)) %>%
                  mutate(within_x1 = max(within_x1)) %>%
                  mutate(within_x2=max(within_x2)) %>%
                  mutate(pathLength1 = max(pathLength1)) %>%
                  mutate(pathLength2 = max(pathLength2))%>%
                  mutate(medFix1 = max(medFix1)) %>%
                  mutate(medFix2 = max(medFix2))%>%
                 top_n(n=1, wt=id) %>%
                mutate(within_x1_pct = within_x1 / Dots_Shown1) %>%
                mutate(within_x2_pct = within_x2 / Dots_Shown2) %>% 
                mutate(within_x_pct_ratio = (within_x1 - within_x2)/((within_x1**2 + within_x2**2)**0.5)) %>%
               mutate(cond=paste(round(Time1),round(Time2),sep="_")) 

data.resp.avs.subs <- data.resp.avs %>%
            
            filter((Trial_End >= 1523639984) & ((within_x1) >  0 & (within_x2 > 0))) %>%
            group_by(Trial_End) %>%
            mutate(within_x_diff = (within_x1 - within_x2)) %>%
            mutate(within_x_ratio = -(within_x1 - within_x2)/(within_x1**2 + within_x2**2)**0.5) %>%
            mutate(within_x_log_diff = -(log(within_x1) - log(within_x2)))  %>%
            mutate(abs_within_x_log_diff = abs(within_x_log_diff))  %>%
  
            mutate(log_Dots_Diff =  log(Dots_Shown1) - log(Dots_Shown2)) %>%
            mutate(Dots_Ratio = (Dots_Shown1 - Dots_Shown2)/(Dots_Shown1**2 + Dots_Shown2**2)**0.5) %>%
            mutate(Abs_Dots_Ratio = abs(Dots_Ratio))  %>%
            mutate(Dots_Counted = Dots_Counted - 1) %>%
            mutate(Score = Score - 1)


subs_cop <- cbind(data.resp.avs.subs)

f_get_weber <- function(whomst) {
  whomst <- whomst[1]
  df <- subset(subs_cop, as.numeric(as.character(subs_cop$pid)) == as.numeric(as.character(whomst)))
  reg <- glm(data=df, I(1-Dots_Counted) ~ Dots_Ratio - 1, family=binomial(link="probit"))
  return(1/(coef(reg)["Dots_Ratio"]))
}



data.resp.avs.subs <- data.resp.avs.subs %>%
            group_by(pid) %>%
            mutate(weber = f_get_weber(pid)) %>%
            mutate(log_PL1=log(pathLength1+1)) %>%
            mutate(log_PL2=log(pathLength2 + 1)) %>%
            mutate(log_PL = log(pathLength2 * pathLength1 + 1)) %>%
            mutate(log_fix1 = log(medFix1 + 1)) %>%
            mutate(log_fix2 = log(medFix2 + 1)) %>%
            mutate(log_fix = log_fix1 + log_fix2) %>%
            rowwise() %>%
            mutate(pctArea= pctArea1 + pctArea2) %>%

            mutate(dens_norm1 = within_x1/pctArea1) %>%
            mutate(dens_norm2 = within_x2/pctArea2) %>%
            mutate(dens_norm = log(dens_norm1) - log(dens_norm2)) %>% 
            mutate(dens_norm_err =dens_norm * (1 * (dens_norm1 < dens_norm2) * (Dots_Shown1 > Dots_Shown2) + 1 * (dens_norm1 > dens_norm2)  * (Dots_Shown1 < Dots_Shown2))) %>% 

            mutate(acc_err = (within_x1 - within_x2) *  (1 * (within_x1 < within_x2) * (Dots_Shown1 > Dots_Shown2) + 1 *  (within_x1 > within_x2) * (Dots_Shown1 < Dots_Shown2) )) %>% 
            #mutate(dens_norm_abs_err = abs(dens_norm_err)) %>% 
            mutate(acc_err_bin  =  1 * (within_x1 < within_x2) * (Dots_Shown1 > Dots_Shown2) - 1 *  (within_x1 > within_x2) * (Dots_Shown1 < Dots_Shown2)) %>% 
            mutate(dens_norm_err_bin  =  1 * (dens_norm1 < dens_norm2) * (Dots_Shown1 > Dots_Shown2) - 1 *  (dens_norm1 > dens_norm2) * (Dots_Shown1 < Dots_Shown2)) %>% 

            ungroup
  

```

```{r, fig.width=7, fig.height=5}

data.resp.avs.subs$cond <- plyr::mapvalues(data.resp.avs.subs$cond, from = c("0_0", "0_1", "1_0", "1_1"), to = c("Short_Short", "Short_Long", "Long_Short", "Long_Long"))
#data.resp.avs.subs$cond <- plyr::mapvalues(data.resp.avs.subs$cond, from = c("0_0", "0_1", "1_0", "1_1"), to = c("S_S", "S_L", "L_S", "L_L"))

  

#SANITY CHECK
ggplot(data=data.resp.avs.subs, aes(x=Dots_Shown1, y=within_x1)) +
     geom_point() + 
      geom_abline() +
      #stat_summary_bin()+
      stat_smooth(method="loess") +

      facet_wrap(~cond) +
      paper_theme_2 



ggplot(data=data.resp.avs.subs, aes(x=abs_within_x_log_diff, y=Score)) +
        binomial_smooth(se=TRUE) +
          geom_hline(yintercept=0.5) +
        geom_vline(xintercept=0.0)+
        ylab("Score") +
        xlab("Absolute seen ratio") +
        theme_light() +
        paper_theme_3

ggplot(data=data.resp.avs.subs, aes(x=within_x_log_diff, y=Dots_Counted, color=cond)) +
        binomial_smooth(se=TRUE) +
          geom_hline(yintercept=0.5) +
        geom_vline(xintercept=0.0)+
        ylab("Guess 2") +
        xlab("Seen ratio") +
        theme_light() +
        paper_theme_3  +
        theme(legend.title=element_blank(), legend.position=c(0.8,0.85)) #+
        #coord_cartesian(xlim=c(-2.1,2.1))
#THIS IS COOL -- SHOWS THAT YOU CAN ACCOUNT FOR ERROR

ggplot(data=data.resp.avs.subs, aes(x=(within_x_ratio ), 
                                          y=Dots_Counted)) +
      geom_point() +
        theme_light() +
        paper_theme_3     # facet_wrap(~cond)
       binomial_smooth(se=TRUE) 


#How well does 
ggplot(data=subset(data.resp.avs.subs, data.resp.avs.subs$dens_norm_err != 0), 
        aes(x=dens_norm_err, y=Dots_Counted, color="Density")) +
#ggplot(data=data.resp.avs.subs, aes(x=dens_norm_err, y=Dots_Counted, color="Density")) +
             stat_summary_bin(bins=4) +
            binomial_smooth() +
          #  binomial_smooth(aes(x=acc_err, y=Dots_Counted, color="Accumulator"))  +
        theme_light() +
        paper_theme_3

ggplot(data=subset(data.resp.avs.subs, data.resp.avs.subs$dens_norm_err != 0), 
        aes(x=dens_norm_err)) +
      geom_histogram(bins=10,aes(fill=factor(Dots_Counted))) +
      paper_theme_2 +
      facet_wrap(~cond, nrow=4) +
      geom_vline(xintercept=0)

ggplot(data=data.resp.avs.subs) + 
        stat_summary(aes(x=acc_err_bin, y=Dots_Counted))  
  
#ggplot(data=data.resp.avs.subs, aes(color=cond)) + 
ggplot(data=data.resp.avs.subs) + 
            stat_summary(aes(x=factor(dens_norm_err_bin), y=Dots_Counted), 
                           geom="bar", size=1., alpha=0.5)  +
          stat_summary(aes(x=factor(dens_norm_err_bin), y=Dots_Counted), 
                           geom="point", size=2.)  +
          stat_summary(aes(x=factor(dens_norm_err_bin), y=Dots_Counted), 
                         geom="errorbar", width=0.25, size=1.)  +
      scale_x_discrete(labels=c("See 2 > 1, falsely", "Correctly estimate", "See 1 > 2, falsely")) +
        xlab("") + ylab("P(Choose 2)")  +
        #facet_wrap(~cond) #+
        theme_light() +
        paper_theme_3

data.resp.avs.subs$cond_ord <- factor(data.resp.avs.subs$cond, levels(factor(data.resp.avs.subs$cond))[c(3,2,1,4)])


data.resp.avs.subs.2 <- subset(data.resp.avs.subs, as.character(data.resp.avs.subs$cond) == "Long_Short" | as.character(data.resp.avs.subs$cond) == "Short_Long")
#data.resp.avs.subs.2 <- subset(data.resp.avs.subs, as.character(data.resp.avs.subs$cond) != "Long_Short" & as.character(data.resp.avs.subs$cond) != "Short_Long")

  
ggplot(data=data.resp.avs.subs.2, aes(x=cond_ord, y=Dots_Counted)) +
          stat_summary(fun.y="mean", geom="point", alpha=0.75, size=2.,position=position_dodge(width=0.2),  aes(color="Participant",shape="Participant", group=Subject)) +
            stat_summary(fun.y="mean", geom="line", alpha=0.5, size=0.8,position=position_dodge(width=0.2),  aes(color="Participant",shape="Participant", group=Subject)) +
          stat_summary(fun.y="mean", geom="point", alpha=1, size=5., aes(color="Group", shape="Group")) +
          stat_summary(fun.data="mean_se", geom="errorbar", width=0.35, aes(color="Group", shape="Group")) +
        theme_light() + 
        paper_theme_3 + 
        geom_hline(yintercept=0.5, alpha=0.5) +

  theme(legend.title=element_blank(), legend.text=element_text(size=16), axis.text.x=element_text(size=18), axis.text.y=element_text(size=18),
            axis.title.x=element_text(size=20), axis.title.y=element_text(size=20), legend.position=c(0.82,0.85)) +
  scale_color_manual(name="a", values=c("Red", "Black"),labels=c("Group", "Participant")) +
        scale_shape_manual(name="a", values=c(19, 17), labels=c("Group", "Participant")) +
            xlab("")  + ylab("p(choose 2)")

ggsave("figs/dots_counted_diff.pdf", width=5,height=4.5)
#ggsave("figs/dots_counted_diff_same.pdf", width=5,height=4.5)

ggplot(data=data.resp.avs.subs.2, aes(x=cond_ord, y=within_x_log_diff)) +
          #geom_violin(adjust=1.5) +
        geom_hline(yintercept=0.0, alpha=0.5) +

            #stat_summary(fun.y="mean", geom="line", alpha=0.75, size=1., linetype="dashed", aes(group=1)) +
          stat_summary(fun.y="mean", geom="point", alpha=0.75, size=2.,position=position_dodge(width=0.2),  aes(color="Participant",shape="Participant", group=Subject)) +
            stat_summary(fun.y="mean", geom="line", alpha=0.5, size=0.8,position=position_dodge(width=0.2),  aes(color="Participant",shape="Participant", group=Subject)) +
          stat_summary(fun.y="mean", geom="point", alpha=1, size=5., aes(color="Group", shape="Group")) +
          stat_summary(fun.data="mean_se", geom="errorbar", width=0.35, aes(color="Group", shape="Group")) +
        theme_light() + 
        paper_theme_3 +
  theme(legend.title=element_blank(), legend.text=element_text(size=16), axis.text.x=element_text(size=18), axis.text.y=element_text(size=18),
            axis.title.x=element_text(size=20), axis.title.y=element_text(size=20), legend.position=c(0.82,0.85)) +
  scale_color_manual(name="a", values=c("Red", "Black"),labels=c("Group", "Participant")) +
        scale_shape_manual(name="a", values=c(19, 17), labels=c("Group", "Participant")) +
            xlab("")  + ylab(expression(F[2]  -  F[1])) 

ggsave("figs/dots_seen_diff.pdf", width=5,height=4.5)
#ggsave("figs/dots_seen_diff_same.pdf", width=5,height=4.5)


levels(factor(data.resp.avs.subs$cond_ord))

data.resp.avs.subs$cond_ord <- factor(data.resp.avs.subs$cond, levels(factor(data.resp.avs.subs$cond))[c(2,1,3,4)])



#summary(glm(data=data.resp.avs.subs, Dots_Counted ~ cond_ord, family=binomial(link="probit")))
#summary(glm(data=data.resp.avs.subs, Dots_Counted ~ Dots_Ratio, family=binomial(link="probit")))
#summary(glm(data=data.resp.avs.subs, Dots_Counted ~ #cond_ord + Dots_Ratio, family=binomial(link="probit")))

#summary(glm(data=data.resp.avs.subs, Dots_Counted ~ Time1 + Time2 + Dots_Ratio, family=binomial(link="probit")))

#summary(glm(data=data.resp.avs.subs, Dots_Counted ~ Time1 + Time2 + Dots_Ratio + within_x_log_diff, family=binomial(link="probit")))


#summary(glm(data=data.resp.avs.subs, Dots_Counted ~ within_x_log_diff + Dots_Ratio, #family=binomial(link="probit")))
#summary(glm(data=data.resp.avs.subs, Dots_Counted ~ within_x_log_diff + Time1 + Time2 + Dots_Ratio, family=binomial(link="probit")))

#summary(glmer(data=data.resp.avs.subs, Dots_Counted ~ within_x_log_diff + Time1 + Time2 + (1+.|Dots_Ratio), family=binomial(link="probit")))


x1 <- subset(data.resp.avs.subs, data.resp.avs.subs$Time1 == .1 & Time2 == .1)
x2 <- subset(data.resp.avs.subs, data.resp.avs.subs$Time1 == 1 & Time2 == .1)
x3 <- subset(data.resp.avs.subs, data.resp.avs.subs$Time1 == .1 & Time2 == 1)
x4 <- subset(data.resp.avs.subs, data.resp.avs.subs$Time1 == 1 & Time2 == 1)
xs <- c(x1,x2,x3,x4)

mean(x1$Dots_Counted)
sqrt(mean(x1$Dots_Counted) * (1 - mean(x1$Dots_Counted)) / (length((x1$Dots_Counted))))
mean(x2$Dots_Counted)
sqrt(mean(x2$Dots_Counted) * (1 - mean(x2$Dots_Counted)) / (length((x2$Dots_Counted))))
mean(x3$Dots_Counted)
sqrt(mean(x3$Dots_Counted) * (1 - mean(x3$Dots_Counted)) / (length((x3$Dots_Counted))))
mean(x4$Dots_Counted)
sqrt(mean(x4$Dots_Counted) * (1 - mean(x4$Dots_Counted)) / length((x4$Dots_Counted)))

```



```{r}
ggplot(data=data.resp.avs.subs) +
              # binomial_smooth(aes(x=weber, y=Score)) 
               stat_summary_bin(bins=5, aes(x=weber, y=Score/Abs_Dots_Ratio)) 


ggplot(data=data.resp.avs.subs, aes(x=weber, y=pathLength1 + pathLength2)) +
              # binomial_smooth(aes(x=weber, y=Score)) 
               stat_summary() +
              stat_smooth(method="lm", span=2)






summary(glm(data=data.resp.avs.subs, Score ~ Abs_Dots_Ratio * weber, family=binomial(link="probit")))
summary(glm(data=data.resp.avs.subs, weber ~ I(pathLength1 + pathLength2)))
summary(glm(data=data.resp.avs.subs, weber ~ I(medFix1 + medFix2)))



```

```{r}



subs <- data.resp.avs.subs %>%
        #group_by(pid, cond) %>%
        group_by(pid) %>%

        #mutate(weber = f_get_weber(pid)) %>%
        mutate(Score=mean(Score)) %>%
        mutate(pathLength1=mean(pathLength1)) %>%
        mutate(pathLength2=mean(pathLength2)) %>%
        mutate(medFix1=mean(medFix1)) %>%
        mutate(medFix2=mean(medFix2)) %>%
        mutate(log_PL1=log(pathLength1+.01)) %>%
        mutate(log_PL2=log(pathLength2+.01)) %>%
        mutate(log_PL = log(pathLength2 + pathLength1)) %>%
        mutate(log_fix1 = log(medFix1 + 1)) %>%
        mutate(log_fix2 = log(medFix2 + 1)) %>%
        mutate(log_fix = log_fix1 + log_fix2)  %>%
        mutate(pctArea1 = mean(pctArea1)) %>%
        mutate(pctArea2 = mean(pctArea2)) %>%

        top_n(n=1,wt=id)



#ggplot(subs, aes(x=log_PL, y=weber, group=cond, color=cond)) +
ggplot(subs, aes(x=pctArea, y=Score)) +
#ggplot(data.resp.avs.subs, aes(x=abs((log_PL1 + log_PL2) - (log(Dots_Shown1) + log(Dots_Shown2))), y=weber)) +
        geom_point() + 
      #binomial_smooth() + 

        #stat_summary_bin(fun.data="mean_cl_boot", bins=9) +
       # stat_summary(fun.data="mean_cl_boot") +
      stat_smooth(method="lm")  +
      #ylim(0,1) +
      #coord_cartesian(ylim=c(0.1,0.3)) +
    # facet_wrap(~cond, scales="free") +
      paper_theme_2

#ggplot(data.resp.avs.subs, aes(x=log_PL, y=weber, group=cond, color=cond)) +
ggplot(subs, aes(x=log_fix, y=weber)) +
        geom_point() +
     # stat_summary_bin(fun.data="mean_cl_boot", bins=9) +
      stat_smooth(method="lm")  +
      #ylim(0,1) +
      #coord_cartesian(ylim=c(0.1,0.3)) +
      facet_wrap(~cond) +
      paper_theme_2 +
      xlab("Average fixation time")





summary(glm(data=subs, Score ~ log_PL, family=binomial(link="probit")))
        

```



```{r}

df <- data.frame(a=c("x","y","z"), b=c(1,2,3), c=c(4,5,6))
df <- melt(df, id=c("a"))

grepl("ab","a")
```